alert("please enter a valid password")
alert("Welcome to js Land HAppy cooding")
alert("hello... I can run JS through my web browsers console ")
console.log(3+5+8)
console.log( 32+45+93*2)
console.log (65-15)
console.log(50*3)
console.log( 2- 1 + 1 +1)
console.log( 2)
console.log( 2- 1+ 1 )
console.log( 2 - 1)
console.log( 2 - 1 + 1 +1)
console.log(--2)